// flow-typed signature: b8ad6cc7757a7dabfc155da02abd89fb
// flow-typed version: <<STUB>>/travis-ci_v^2.2.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-ci'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-ci' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'travis-ci/bin/travis-ci' {
  declare module.exports: any
}

declare module 'travis-ci/lib/travis-ci' {
  declare module.exports: any
}

declare module 'travis-ci/lib/travis-http' {
  declare module.exports: any
}

// Filename aliases
declare module 'travis-ci/bin/travis-ci.js' {
  declare module.exports: $Exports<'travis-ci/bin/travis-ci'>
}
declare module 'travis-ci/lib/travis-ci.js' {
  declare module.exports: $Exports<'travis-ci/lib/travis-ci'>
}
declare module 'travis-ci/lib/travis-http.js' {
  declare module.exports: $Exports<'travis-ci/lib/travis-http'>
}
